### ISSUE TITLE
安装使用 mysql的python3 mysqlclient相关问题

### ISSUE THREAD

**Issue by yuandongx** [zz-it-auto/itauto#6]
···
root@e90c34c2c22f:/www/itauto# pip3 install mysqlclient
Looking in indexes: https://mirrors.huaweicloud.com/repository/pypi/simple
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.huaweicloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting mysqlclient
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mirrors.huaweicloud.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://mirrors.huaweicloud.com/repository/pypi/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz (87 kB)
     |████████████████████████████████| 87 kB 2.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-re0gdfg3/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-re0gdfg3/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-re0gdfg3/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-re0gdfg3/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-re0gdfg3/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-re0gdfg3/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-re0gdfg3/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

···

**Comment by yuandongx** [comment]
解决方案：
             安装libmysqlclient-dev包即可，如果还有问题，可以安装python-dev。
        输入指令：apt-get install libmysqlclient-dev python3-dev   即可解决此问题

**Comment by yuandongx** [comment]
root@e90c34c2c22f:/www/itauto# apt-get install libmysqlclient-dev python3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
The following additional packages will be installed:
  libmysqlclient21 libssl-dev
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  libmysqlclient-dev libmysqlclient21 libssl-dev
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 4329 kB of archives.
After this operation, 25.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libmysqlclient21 amd64 8.0.21-0ubuntu0.20.04.4 [1222 kB]
Get:2 http://mirrors.aliyun.com/ubuntu focal/main amd64 libssl-dev amd64 1.1.1f-1ubuntu2 [1582 kB]
Get:3 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libmysqlclient-dev amd64 8.0.21-0ubuntu0.20.04.4 [1526 kB]
Fetched 4329 kB in 1s (3405 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmysqlclient21:amd64.
(Reading database ... 21869 files and directories currently installed.)
Preparing to unpack .../libmysqlclient21_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
Unpacking libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Selecting previously unselected package libssl-dev:amd64.
Preparing to unpack .../libssl-dev_1.1.1f-1ubuntu2_amd64.deb ...
Unpacking libssl-dev:amd64 (1.1.1f-1ubuntu2) ...
Selecting previously unselected package libmysqlclient-dev.
Preparing to unpack .../libmysqlclient-dev_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
Unpacking libmysqlclient-dev (8.0.21-0ubuntu0.20.04.4) ...
Setting up mysql-server-8.0 (8.0.21-0ubuntu0.20.04.4) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
Renaming removed key_buffer and myisam-recover options (if present)
Cannot stat file /proc/387/fd/0: Permission denied
Cannot stat file /proc/387/fd/1: Permission denied
Cannot stat file /proc/387/fd/2: Permission denied
Cannot stat file /proc/387/fd/3: Permission denied
Cannot stat file /proc/387/fd/4: Permission denied
Cannot stat file /proc/387/fd/5: Permission denied
Cannot stat file /proc/387/fd/6: Permission denied
Cannot stat file /proc/387/fd/7: Permission denied
Cannot stat file /proc/387/fd/8: Permission denied
Cannot stat file /proc/387/fd/9: Permission denied
Cannot stat file /proc/387/fd/10: Permission denied
Cannot stat file /proc/387/fd/11: Permission denied
Cannot stat file /proc/387/fd/12: Permission denied
Cannot stat file /proc/387/fd/13: Permission denied
Cannot stat file /proc/387/fd/14: Permission denied
Cannot stat file /proc/387/fd/15: Permission denied
Cannot stat file /proc/387/fd/16: Permission denied
Cannot stat file /proc/387/fd/17: Permission denied
Cannot stat file /proc/387/fd/18: Permission denied
Cannot stat file /proc/387/fd/19: Permission denied
Cannot stat file /proc/387/fd/20: Permission denied
Cannot stat file /proc/387/fd/21: Permission denied
Cannot stat file /proc/387/fd/22: Permission denied
Cannot stat file /proc/387/fd/23: Permission denied
Cannot stat file /proc/387/fd/24: Permission denied
Cannot stat file /proc/387/fd/25: Permission denied
Cannot stat file /proc/387/fd/26: Permission denied
Cannot stat file /proc/387/fd/27: Permission denied
Cannot stat file /proc/387/fd/28: Permission denied
mysqld will log errors to /var/log/mysql/error.log
mysqld is running as pid 484
Error: Unable to shut down server with process id 484
dpkg: error processing package mysql-server-8.0 (--configure):
 installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
Setting up libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Setting up libssl-dev:amd64 (1.1.1f-1ubuntu2) ...
Setting up libmysqlclient-dev (8.0.21-0ubuntu0.20.04.4) ...
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-server-8.0; however:
  Package mysql-server-8.0 is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 mysql-server-8.0
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
W: Operation was interrupted before it could finish
root@e90c34c2c22f:/www/itauto# top
top - 08:50:05 up 17 min,  0 users,  load average: 0.16, 0.12, 0.18
Tasks:   6 total,   1 running,   3 sleeping,   0 stopped,   2 zombie
%Cpu(s):  1.0 us,  1.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1987.8 total,    475.6 free,    705.4 used,    806.8 buff/cache
MiB Swap:   2048.0 total,   2046.0 free,      2.0 used.   1121.9 avail Mem

**Comment by yuandongx** [comment]
> root@e90c34c2c22f:/www/itauto# apt-get install libmysqlclient-dev python3-dev
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> python3-dev is already the newest version (3.8.2-0ubuntu2).
> python3-dev set to manually installed.
> The following additional packages will be installed:
> libmysqlclient21 libssl-dev
> Suggested packages:
> libssl-doc
> The following NEW packages will be installed:
> libmysqlclient-dev libmysqlclient21 libssl-dev
> 0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
> 2 not fully installed or removed.
> Need to get 4329 kB of archives.
> After this operation, 25.2 MB of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libmysqlclient21 amd64 8.0.21-0ubuntu0.20.04.4 [1222 kB]
> Get:2 http://mirrors.aliyun.com/ubuntu focal/main amd64 libssl-dev amd64 1.1.1f-1ubuntu2 [1582 kB]
> Get:3 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libmysqlclient-dev amd64 8.0.21-0ubuntu0.20.04.4 [1526 kB]
> Fetched 4329 kB in 1s (3405 kB/s)
> debconf: delaying package configuration, since apt-utils is not installed
> Selecting previously unselected package libmysqlclient21:amd64.
> (Reading database ... 21869 files and directories currently installed.)
> Preparing to unpack .../libmysqlclient21_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
> Unpacking libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
> Selecting previously unselected package libssl-dev:amd64.
> Preparing to unpack .../libssl-dev_1.1.1f-1ubuntu2_amd64.deb ...
> Unpacking libssl-dev:amd64 (1.1.1f-1ubuntu2) ...
> Selecting previously unselected package libmysqlclient-dev.
> Preparing to unpack .../libmysqlclient-dev_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
> Unpacking libmysqlclient-dev (8.0.21-0ubuntu0.20.04.4) ...
> Setting up mysql-server-8.0 (8.0.21-0ubuntu0.20.04.4) ...
> debconf: unable to initialize frontend: Dialog
> debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
> debconf: falling back to frontend: Readline
> invoke-rc.d: could not determine current runlevel
> invoke-rc.d: policy-rc.d denied execution of stop.
> Renaming removed key_buffer and myisam-recover options (if present)
> Cannot stat file /proc/387/fd/0: Permission denied
> Cannot stat file /proc/387/fd/1: Permission denied
> Cannot stat file /proc/387/fd/2: Permission denied
> Cannot stat file /proc/387/fd/3: Permission denied
> Cannot stat file /proc/387/fd/4: Permission denied
> Cannot stat file /proc/387/fd/5: Permission denied
> Cannot stat file /proc/387/fd/6: Permission denied
> Cannot stat file /proc/387/fd/7: Permission denied
> Cannot stat file /proc/387/fd/8: Permission denied
> Cannot stat file /proc/387/fd/9: Permission denied
> Cannot stat file /proc/387/fd/10: Permission denied
> Cannot stat file /proc/387/fd/11: Permission denied
> Cannot stat file /proc/387/fd/12: Permission denied
> Cannot stat file /proc/387/fd/13: Permission denied
> Cannot stat file /proc/387/fd/14: Permission denied
> Cannot stat file /proc/387/fd/15: Permission denied
> Cannot stat file /proc/387/fd/16: Permission denied
> Cannot stat file /proc/387/fd/17: Permission denied
> Cannot stat file /proc/387/fd/18: Permission denied
> Cannot stat file /proc/387/fd/19: Permission denied
> Cannot stat file /proc/387/fd/20: Permission denied
> Cannot stat file /proc/387/fd/21: Permission denied
> Cannot stat file /proc/387/fd/22: Permission denied
> Cannot stat file /proc/387/fd/23: Permission denied
> Cannot stat file /proc/387/fd/24: Permission denied
> Cannot stat file /proc/387/fd/25: Permission denied
> Cannot stat file /proc/387/fd/26: Permission denied
> Cannot stat file /proc/387/fd/27: Permission denied
> Cannot stat file /proc/387/fd/28: Permission denied
> mysqld will log errors to /var/log/mysql/error.log
> mysqld is running as pid 484
> Error: Unable to shut down server with process id 484
> dpkg: error processing package mysql-server-8.0 (--configure):
> installed mysql-server-8.0 package post-installation script subprocess returned error exit status 1
> Setting up libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
> Setting up libssl-dev:amd64 (1.1.1f-1ubuntu2) ...
> Setting up libmysqlclient-dev (8.0.21-0ubuntu0.20.04.4) ...
> dpkg: dependency problems prevent configuration of mysql-server:
> mysql-server depends on mysql-server-8.0; however:
> Package mysql-server-8.0 is not configured yet.
> 
> dpkg: error processing package mysql-server (--configure):
> dependency problems - leaving unconfigured
> Processing triggers for libc-bin (2.31-0ubuntu9) ...
> Errors were encountered while processing:
> mysql-server-8.0
> mysql-server
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> W: Operation was interrupted before it could finish
> root@e90c34c2c22f:/www/itauto# top
> top - 08:50:05 up 17 min, 0 users, load average: 0.16, 0.12, 0.18
> Tasks: 6 total, 1 running, 3 sleeping, 0 stopped, 2 zombie
> %Cpu(s): 1.0 us, 1.0 sy, 0.0 ni, 98.0 id, 0.0 wa, 0.0 hi, 0.0 si, 0.0 st
> MiB Mem : 1987.8 total, 475.6 free, 705.4 used, 806.8 buff/cache
> MiB Swap: 2048.0 total, 2046.0 free, 2.0 used. 1121.9 avail Mem

可能出现的问题，是因为mysql安装的问题，而且  权限不够，目前的解办法是 卸载mysql-server或者找一个没有装过mysql的系统重装

**Comment by yuandongx** [comment]
现在问题已经解决
